pr:
  branches:
    include:
    - master
trigger:
  batch: true
  branches:
    include:
    - master
stages:
- stage: __default
  jobs:
  - job: Job
    pool:
      name: Azure Pipelines
      vmImage: windows-latest
    steps:
    - task: DotNetCoreCLI@2
      displayName: Restore Packages
      inputs:
        command: restore
        projects: '**/*.sln'
        feedsToUse: config
        nugetConfigPath: nuget.config
    - task: DotNetCoreCLI@2
      displayName: Build solution
      inputs:
        command: build
        projects: '**/*.sln'
        arguments: --configuration Release --no-restore
    - task: DotNetCoreCLI@2
      displayName: Execute Unit Tests
      inputs:
        command: test
        projects: '**/*.UnitTests.csproj'
        arguments: --no-build  --configuration Release  --collect "Code coverage"
        testRunTitle: RecruitingDataSync - Unit Tests